Repository paion-data/immutable-infrastructure-as-a-service, pull requests merged in 2024-05, with the labels that each got.

#22 Enable Algolia search
  .github/workflows/ci-cd.yml
  docs/docusaurus.config.ts
Labels: DOCUMENTATION, MERGEABLE

#33 Add Packer and Terraform Linting to CI/CD
  .github/workflows/ci-cd.yml
  hashicorp/elk/images/aws-elk.source.pkr.hcl
  hashicorp/elk/instances/aws-elk.tf
  hashicorp/kong-api-gateway/images/aws/aws-kong.source.pkr.hcl
  hashicorp/kong-api-gateway/images/kong.build.pkr.hcl
  hashicorp/kong-api-gateway/instances/alicloud/ali-kong.tf
  hashicorp/kong-api-gateway/instances/aws/aws-kong.tf
  hashicorp/machine-learning/images/aws-ml.source.pkr.hcl
  hashicorp/machine-learning/images/mlflow-docker/aws-ml.build.pkr.hcl
  hashicorp/machine-learning/instances/aws-ml.base.tf
  hashicorp/machine-learning/instances/mlflow-docker/aws-ml.tf
  hashicorp/react/images/aws-react.build.pkr.hcl
  hashicorp/react/images/aws-react.pkr.hcl
  hashicorp/react/images/aws-react.variables.pkr.hcl
  hashicorp/react/instances/aws-react.tf
  hashicorp/webservice/images/aws-ws.source.pkr.hcl
  hashicorp/webservice/instances/aws-ws.base.tf
  hashicorp/webservice/instances/basic/aws-ws.tf
  hashicorp/webservice/instances/ssl/aws-ws.tf
  tests/elk/images/aws-elk.packer.pkr.hcl
  tests/kong-api-gateway/images/ali-kong.packer.pkr.hcl
  tests/machine-learning/images/mlflow-docker/aws-ml.packer.pkr.hcl
  tests/machine-learning/images/mlflow-docker/aws-ml.source.pkr.hcl
  tests/react/images/aws-react.test.pkr.hcl
  tests/webservice/images/aws-ws.packer.pkr.hcl
Labels: NEED 1 REVIEW

#35 Update Kong deployment script
  adaptors/screwdriver-cd/templates/kong-api-gateway-sd-template.yaml
  hashicorp/kong-api-gateway/images/alicloud/ali-kong.packer.pkr.hcl
  hashicorp/kong-api-gateway/images/aws/aws-kong.packer.pkr.hcl
  hashicorp/kong-api-gateway/instances/alicloud/ali-kong.tf
  hashicorp/kong-api-gateway/instances/aws/aws-kong.tf
  hashicorp/kong-api-gateway/scripts/ali-kong-tf-init.sh
  tests/kong-api-gateway/images/ali-kong.packer.pkr.hcl
Labels: MERGEABLE, REFACTORING

#32 Support deploying Webservice to Alicloud
  .github/workflows/ci-cd.yml
  adaptors/screwdriver-cd/templates/jersey-webservice-template-basic-sd-template.yaml
  hashicorp/webservice/images/alicloud/ali-ws.packer.pkr.hcl
  hashicorp/webservice/images/alicloud/ali-ws.source.pkr.hcl
  hashicorp/webservice/images/alicloud/ws.build.pkr.hcl
  hashicorp/webservice/images/aws/aws-ws.packer.pkr.hcl
  hashicorp/webservice/images/aws/aws-ws.source.pkr.hcl
  hashicorp/webservice/images/aws/basic/aws-ws.build.pkr.hcl
  hashicorp/webservice/images/aws/ssl/aws-ws.build.pkr.hcl
  hashicorp/webservice/images/aws/ssl/nginx-ssl.conf
  hashicorp/webservice/instances/alicloud/ali-ws.tf
  hashicorp/webservice/instances/aws/aws-ws.base.tf
  hashicorp/webservice/instances/aws/basic/aws-ws.tf
  hashicorp/webservice/instances/aws/ssl/aws-ws.tf
  hashicorp/webservice/scripts/ws-tf-init-basic.sh
  tests/webservice/images/aws-ws.auto.pkrvars.hcl
  tests/webservice/images/aws/aws-ws.auto.pkrvars.hcl
  tests/webservice/images/aws/aws-ws.packer.pkr.hcl
  tests/webservice/images/aws/aws-ws.source.pkr.hcl
  tests/webservice/images/aws/filebeat.yml
  tests/webservice/images/aws/run-tests.sh
  tests/webservice/images/aws/test-webservice-1.0-SNAPSHOT.war
Labels: MERGEABLE, NEW FEATURE

#36 Register webservice to kong gateway
  hashicorp/webservice/instances/alicloud/ali-ws.tf
Labels: MERGEABLE, NEW FEATURE

#34 Kong Terraform integration Github Action Job
  .github/workflows/ci-cd.yml
  tests/kong-api-gateway/images/ali-kong.source.pkr.hcl
  tests/kong-api-gateway/images/kong.build.pkr.hcl
  tests/kong-api-gateway/images/run-tests.sh
  tests/kong-api-gateway/instances/kong.tftest.hcl
Labels: CI/CD, MERGEABLE

#45 简化 React Packer 配置
  .github/workflows/ci-cd.yml
  LICENSE
  docs/docs/development.md
  docs/docs/img/packer-fmt-error.png
  docs/docs/img/resync-pipeline.png
  docs/docs/img/sd-oauth-warning.png
  docs/docs/kong-api-gateway/index.mdx
  docs/docs/kong-api-gateway/screwdriver-cd-deployment.md
  docs/docs/setup.md
  docs/docs/troubleshooting.md
  hashicorp/react/images/ali-react.pkr.hcl
  hashicorp/react/images/ali-react.variables.pkr.hcl
  hashicorp/react/images/react.build.pkr.hcl
  hashicorp/react/instances/ali-react.tf
Labels: CI/CD, DOCUMENTATION, NEED 1 REVIEW, REFACTORING

#51 Update ubuntu image
  hashicorp/react/images/ali-react.pkr.hcl
Labels: CONFIG, MERGEABLE

#49 Supports React domain name binding
  hashicorp/react/instances/ali-react.tf
Labels: MERGEABLE, NEW FEATURE

#53 fix react tf script
  hashicorp/react/instances/ali-react.tf
Labels: BUG, MERGEABLE

#56 Add vswitch id for React development
  hashicorp/react/instances/ali-react.tf
  hashicorp/react/scripts/react-tf-init.sh
Labels: CONFIG, MERGEABLE

#52 Enhance documentation on 'updating ECS image regularly'
  docs/docs/troubleshooting.md
Labels: DOCUMENTATION, MERGEABLE

#58 Add 'AliyunDNSFullAccess' to the list of required RAM permission list in 'setup' manual
  docs/docs/setup.md
Labels: DOCUMENTATION, NEED 1 REVIEW

#60 Start Nginx and save the serve log
  hashicorp/react/scripts/react-tf-init.sh
Labels: CONFIG, NEED 1 REVIEW

#62 Fix Syntax Error in init script
  hashicorp/kong-api-gateway/scripts/ali-kong-tf-init.sh
  hashicorp/react/scripts/react-tf-init.sh
Labels: BUG, MERGEABLE

#64 Fix react init script
  hashicorp/react/scripts/react-tf-init.sh
Labels: BUG, MERGEABLE

#65 Refine the domain binding in React Deployment
  hashicorp/react/instances/ali-react.tf
Labels: MERGEABLE, NEW FEATURE

#68 Fix naming error
  hashicorp/react/instances/ali-react.tf
Labels: BUG, MERGEABLE

#69 Fix naming error
  hashicorp/react/instances/ali-react.tf
Labels: BUG, MERGEABLE
