Repository paion-data/immutable-infrastructure-as-a-service, pull requests merged in 2024-04, with the labels that each got.

#16 Update naming
  .github/workflows/ci-cd.yml
  README.md
  docs/docs/img/iiaas.drawio
  docs/docs/img/iiaas.png
  docs/docs/intro.md
  docs/docs/kong-api-gateway/_category_.json
  docs/docs/kong-api-gateway/index.md
  docs/docs/kong-api-gateway/screwdriver-cd-deployment.md
  hashicorp/kong-api-gateway/images/ali-kong.build.pkr.hcl
  hashicorp/kong-api-gateway/images/ali-kong.packer.pkr.hcl
  tests/elk/images/aws-elk.source.pkr.hcl
  tests/kong-api-gateway/images/ali-kong.packer.pkr.hcl
  tests/machine-learning/images/mlflow-docker/aws-ml.source.pkr.hcl
  tests/react/images/aws-react.test.pkr.hcl
  tests/webservice/images/aws-ws.source.pkr.hcl
Labels: DOCUMENTATION, MERGEABLE

#17 Add troubleshooting documentation
  README.md
  docs/docs/img/sd-oauth-warning.png
  docs/docs/setup.md
  docs/docs/troubleshooting.md
Labels: DOCUMENTATION, NEED 1 REVIEW

#18 Fix documentation syntax error
  docs/docs/img/resync-pipeline.png
  docs/docs/setup.md
Labels: BUG, DOCUMENTATION, MERGEABLE

#19 Develop kong through Screwdriver
  .gitignore
  adaptors/screwdriver-cd/templates/kong-api-gateway-sd-template.yaml
  hashicorp/kong-api-gateway/instances/alicloud/ali-kong.tf
Labels: MERGEABLE, NEW FEATURE
